name: bones_api
description: Bones_API - A powerful API backend framework for Dart. It comes with a built-in HTTP Server, route handler, entity handler, SQL translator, and DB adapters.
version: 1.5.18
homepage: https://github.com/Colossus-Services/bones_api

environment:
  sdk: '>=3.2.0 <4.0.0'

executables:
  bones_api:

dependencies:
  async_extension: ^1.2.5
  async_events: ^1.0.12
  reflection_factory: ^2.2.5
  statistics: ^1.0.26
  swiss_knife: ^3.1.5
  data_serializer: ^1.0.12
  shared_map: ^1.1.7
  graph_explorer: ^1.0.2
  ascii_art_tree: ^1.0.6
  map_history: ^1.0.3
  dart_spawner: ^1.1.0
  yaml_writer: ^1.0.3
  mercury_client: ^2.2.0
  project_template: ^1.0.2
  resource_portable: ^3.1.0
  docker_commander: ^2.1.5
  args_simple: ^1.1.0
  shelf_letsencrypt: ^1.2.2
  shelf: ^1.4.1
  shelf_gzip: ^4.1.0
  shelf_static: ^1.1.2
  args: ^2.4.2
  meta: ^1.11.0
  petitparser: ^6.0.2
  hotreloader: ^4.1.0
  logging: ^1.1.0
  collection: ^1.18.0
  mime: ^1.0.4
  postgres: ^2.6.3
  mysql1: ^0.20.0
  gcloud: ^0.8.11
  yaml: ^3.1.2
  crypto: ^3.0.3
  path: ^1.8.3
  archive: ^3.4.6
  stream_channel: ^2.1.2
  http: ^1.1.0
  googleapis_auth: ^1.4.1
  crclib: ^3.0.0

dev_dependencies:
  lints: ^3.0.0
  build_runner: ^2.4.6
  build_verify: ^3.1.0
  test: ^1.24.7
  pubspec: ^2.3.0
  dependency_validator: ^3.2.3
  coverage: ^1.7.1
  vm_service: ^13.0.0

#dependency_overrides:
#  shared_map:
#    path: ../shared_map
#  args_simple:
#    path: ../args_simple
#  graph_explorer:
#    path: ../graph_explorer
#  ascii_art_tree:
#    path: ../ascii_art_tree
#  data_serializer:
#    path: ../data_serializer
#  async_events:
#    path: ../async_events
#  map_history:
#    path: ../map_history
#  mercury_client:
#    path: ../mercury_client
#  async_extension:
#    path: ../async_extension
#  dart_spawner:
#    path: ../dart_spawner
#  reflection_factory:
#    path: ../reflection_factory
#  statistics:
#    path: ../statistics
#  docker_commander:
#    path: ../docker_commander
#  shelf_letsencrypt:
#    path: ../shelf_letsencrypt
#  swiss_knife:
#    path: ../swiss_knife
