name: bones_api
description: Bones_API - A powerful API backend framework for Dart. It comes with a built-in HTTP Server, route handler, entity handler, SQL translator, and DB adapters.
version: 1.8.0
homepage: https://github.com/Colossus-Services/bones_api

environment:
  sdk: '>=3.5.0 <4.0.0'

executables:
  bones_api:

dependencies:
  async_extension: ^1.2.12
  async_events: ^1.2.0
  reflection_factory: ^2.4.7
  statistics: ^1.1.3
  swiss_knife: ^3.2.2
  data_serializer: ^1.2.1
  shared_map: ^1.1.9
  graph_explorer: ^1.0.2
  ascii_art_tree: ^1.0.6
  map_history: ^1.0.4
  dart_spawner: ^1.1.0
  yaml_writer: ^2.0.1
  mercury_client: ^2.2.4
  project_template: ^1.1.0
  resource_portable: ^3.1.0
  docker_commander: ^2.1.7
  args_simple: ^1.1.0
  shelf_letsencrypt: ^2.0.0
  shelf: ^1.4.2
  shelf_gzip: ^4.1.0
  shelf_static: ^1.1.3
  args: ^2.6.0
  meta: ^1.16.0
  petitparser: ^6.0.2
  hotreloader: ^4.2.0
  logging: ^1.3.0
  collection: ^1.18.0
  mime: ^1.0.6
  postgres: ^2.6.4
  mysql1: ^0.20.0
  gcloud: ^0.8.18
  yaml: ^3.1.2
  crypto: ^3.0.6
  path: ^1.9.1
  archive: ^3.6.1
  stream_channel: ^2.1.2
  http: ^1.2.2
  googleapis_auth: ^1.6.0
  crclib: ^3.0.0

dev_dependencies:
  lints: ^4.0.0
  build_runner: ^2.4.13
  build_verify: ^3.1.0
  test: ^1.25.12
  pubspec: ^2.3.0
  dependency_validator: ^4.1.2
  coverage: ^1.11.1
  vm_service: ^13.0.0

#dependency_overrides:
#  shared_map:
#    path: ../shared_map
#  shelf_letsencrypt:
#    path: ../shelf_letsencrypt
#  args_simple:
#    path: ../args_simple
#  graph_explorer:
#    path: ../graph_explorer
#  ascii_art_tree:
#    path: ../ascii_art_tree
#  data_serializer:
#    path: ../data_serializer
#  async_events:
#    path: ../async_events
#  map_history:
#    path: ../map_history
#  mercury_client:
#    path: ../mercury_client
#  async_extension:
#    path: ../async_extension
#  dart_spawner:
#    path: ../dart_spawner
#  reflection_factory:
#    path: ../reflection_factory
#  statistics:
#    path: ../statistics
#  docker_commander:
#    path: ../docker_commander
#  shelf_letsencrypt:
#    path: ../shelf_letsencrypt
#  swiss_knife:
#    path: ../swiss_knife
