name: bones_api
description: Bones_API - A Powerful API backend framework for Dart. Comes with a built-in HTTP Server, routes handler, entity handler, SQL translator, and DB adapters.
version: 1.1.12
homepage: https://github.com/Colossus-Services/bones_api

environment:
  sdk: '>=2.14.0 <3.0.0'

executables:
  bones_api:

dependencies:
  shelf: ^1.2.0
  shelf_gzip: ^4.0.0
  shelf_static: ^1.1.0
  shelf_letsencrypt: ^1.0.0
  async_extension: ^1.0.9
  dart_spawner: ^1.0.6
  args: ^2.2.0
  reflection_factory: ^1.0.27
  meta: ^1.7.0
  data_serializer: ^1.0.6
  statistics: ^1.0.20
  petitparser: ^4.2.0
  hotreloader: ^3.0.1
  logging: ^1.0.1
  collection: ^1.15.0
  mime: ^1.0.0
  postgres: ^2.4.3
  mysql1: ^0.19.2
  yaml: ^3.1.0
  yaml_writer: ^1.0.1
  mercury_client: ^2.1.4
  project_template: ^1.0.2
  resource_portable: ^3.0.0
  crypto: ^3.0.1
  path: ^1.8.1
  swiss_knife: ^3.0.8

dev_dependencies:
  lints: ^1.0.1
  build_runner: ^2.1.5
  build_verify: ^3.0.0
  test: ^1.19.5
  docker_commander: ^2.0.13
  pubspec: ^2.0.1
  dependency_validator: ^3.1.2
  coverage: ^1.0.3

#dependency_overrides:
#  mercury_client:
#    path: ../mercury_client
#  async_extension:
#    path: ../async_extension
#  dart_spawner:
#    path: ../dart_spawner
#  reflection_factory:
#    path: ../reflection_factory
#  docker_commander:
#    path: ../docker_commander

