name: bones_api
description: Bones_API - A Powerful API backend framework for Dart. Comes with a built-in HTTP Server, routes handler, entity handler, SQL translator, and DB adapters.
version: 1.2.6
homepage: https://github.com/Colossus-Services/bones_api

environment:
  sdk: '>=2.15.0 <3.0.0'

executables:
  bones_api:

dependencies:
  shelf: ^1.3.1
  shelf_gzip: ^4.0.0
  shelf_static: ^1.1.1
  shelf_letsencrypt: ^1.0.0
  async_extension: ^1.0.9
  dart_spawner: ^1.0.6
  args: ^2.3.1
  reflection_factory: ^1.2.0
  meta: ^1.7.0
  data_serializer: ^1.0.7
  statistics: ^1.0.21
  petitparser: ^5.0.0
  hotreloader: ^3.0.5
  logging: ^1.0.1
  collection: ^1.15.0
  mime: ^1.0.0
  postgres: ^2.4.5
  mysql1: ^0.20.0
  yaml: ^3.1.1
  yaml_writer: ^1.0.1
  mercury_client: ^2.1.6
  project_template: ^1.0.2
  resource_portable: ^3.0.0
  crypto: ^3.0.2
  path: ^1.8.1
  swiss_knife: ^3.1.0
  map_history: ^1.0.2
  docker_commander: ^2.0.15

dev_dependencies:
  lints: ^2.0.0
  build_runner: ^2.1.5
  build_verify: ^3.0.0
  test: ^1.21.4
  pubspec: ^2.0.1
  dependency_validator: ^3.2.2
  coverage: ^1.3.2

#dependency_overrides:
#  mercury_client:
#    path: ../mercury_client
#  async_extension:
#    path: ../async_extension
#  dart_spawner:
#    path: ../dart_spawner
#  reflection_factory:
#    path: ../reflection_factory
#  docker_commander:
#    path: ../docker_commander

