name: bones_api
description: Bones_API - A Powerful API backend framework for Dart. Comes with a built-in HTTP Server, routes handler, entity handler, SQL translator, and DB adapters.
version: 1.0.11
homepage: https://github.com/Colossus-Services/bones_api

environment:
  sdk: '>=2.13.0 <3.0.0'

executables:
  bones_api:

dependencies:
  shelf: ^1.2.0
  async_extension: ^1.0.7
  dart_spawner: ^1.0.5
  args: ^2.2.0
  reflection_factory: ^1.0.8
  petitparser: ^4.2.0
  hotreloader: ^3.0.1
  logging: ^1.0.1
  collection: ^1.15.0
  mime: ^1.0.0
  postgres: ^2.4.1+2
  yaml: ^3.1.0
  yaml_writer: ^1.0.1
  mercury_client: ^2.1.0

dev_dependencies:
  lints: ^1.0.1
  build_runner: ^2.1.1
  build_verify: ^2.0.0
  test: ^1.17.9
  docker_commander: ^2.0.12
  pubspec: ^2.0.1
  path: ^1.8.0
  dependency_validator: ^3.1.0
  test_cov: ^1.0.1

#dependency_overrides:
#  async_extension:
#    path: ../async_extension
#  dart_spawner:
#    path: ../dart_spawner
#  reflection_factory:
#    path: ../reflection_factory
#  docker_commander:
#    path: ../docker_commander

