name: bones_api
description: Bones_API - A Powerful API backend framework for Dart. Comes with a built-in HTTP Server, routes handler, entity handler, SQL translator, and DB adapters.
version: 1.3.60
homepage: https://github.com/Colossus-Services/bones_api

environment:
  sdk: '>=2.18.0 <3.0.0'

executables:
  bones_api:

dependencies:
  shelf: ^1.4.0
  shelf_gzip: ^4.0.1
  shelf_static: ^1.1.1
  shelf_letsencrypt: ^1.1.1
  async_extension: ^1.1.0
  dart_spawner: ^1.0.6
  args: ^2.4.0
  reflection_factory: ^2.0.5
  meta: ^1.7.0
  statistics: ^1.0.24
  petitparser: ^5.2.0
  hotreloader: ^3.0.5
  logging: ^1.1.0
  collection: ^1.17.0
  mime: ^1.0.4
  postgres: ^2.6.1
  mysql1: ^0.20.0
  gcloud: ^0.8.7
  yaml: ^3.1.1
  yaml_writer: ^1.0.3
  mercury_client: ^2.1.8
  project_template: ^1.0.2
  resource_portable: ^3.0.1
  crypto: ^3.0.2
  path: ^1.8.3
  swiss_knife: ^3.1.3
  map_history: ^1.0.3
  docker_commander: ^2.0.15
  data_serializer: ^1.0.7
  async_events: ^1.0.9
  archive: ^3.3.6
  stream_channel: ^2.1.1
  http: ^0.13.5
  googleapis_auth: ^1.4.0
  crclib: ^3.0.0

dev_dependencies:
  lints: ^2.0.1
  build_runner: ^2.3.3
  build_verify: ^3.1.0
  test: ^1.23.1
  pubspec: ^2.3.0
  dependency_validator: ^3.2.2
  coverage: ^1.6.3

#dependency_overrides:
#  async_events:
#    path: ../async_events
#  map_history:
#    path: ../map_history
#  mercury_client:
#    path: ../mercury_client
#  async_extension:
#    path: ../async_extension
#  dart_spawner:
#    path: ../dart_spawner
#  reflection_factory:
#    path: ../reflection_factory
#  statistics:
#    path: ../statistics
#  docker_commander:
#    path: ../docker_commander
#  shelf_letsencrypt:
#    path: ../shelf_letsencrypt
