name: bones_api
description: Bones_API - Simple and easy API framework, with routes and HTTP Server.
version: 1.0.4
homepage: https://github.com/Colossus-Services/bones_api

environment:
  sdk: '>=2.13.0 <3.0.0'

executables:
  bones_api:

dependencies:
  shelf: ^1.2.0
  async_extension: ^1.0.4
  dart_spawner: ^1.0.2
  args: ^2.0.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.9
  dependency_validator: ^3.1.0
  test_cov: ^1.0.1
