name: bones_api
description: Bones_API - A powerful API backend framework for Dart. It comes with a built-in HTTP Server, route handler, entity handler, SQL translator, and DB adapters.
version: 1.4.28
homepage: https://github.com/Colossus-Services/bones_api

environment:
  sdk: '>=3.0.0 <4.0.0'

executables:
  bones_api:

dependencies:
  shelf: ^1.4.1
  shelf_gzip: ^4.0.1
  shelf_static: ^1.1.2
  shelf_letsencrypt: ^1.2.2
  async_extension: ^1.2.5
  dart_spawner: ^1.1.0
  args: ^2.4.2
  reflection_factory: ^2.2.1
  meta: ^1.9.1
  statistics: ^1.0.25
  petitparser: ^5.4.0
  hotreloader: ^3.0.6
  logging: ^1.1.0
  collection: ^1.17.2
  mime: ^1.0.4
  postgres: ^2.6.2
  mysql1: ^0.20.0
  gcloud: ^0.8.11
  yaml: ^3.1.2
  yaml_writer: ^1.0.3
  mercury_client: ^2.2.0
  project_template: ^1.0.2
  resource_portable: ^3.1.0
  crypto: ^3.0.3
  path: ^1.8.3
  swiss_knife: ^3.1.5
  map_history: ^1.0.3
  docker_commander: ^2.1.0
  data_serializer: ^1.0.10
  async_events: ^1.0.12
  archive: ^3.3.8
  stream_channel: ^2.1.2
  http: ^1.1.0
  googleapis_auth: ^1.4.1
  crclib: ^3.0.0

dev_dependencies:
  lints: ^2.1.1
  build_runner: ^2.4.6
  build_verify: ^3.1.0
  test: ^1.24.6
  pubspec: ^2.3.0
  dependency_validator: ^3.2.2
  coverage: ^1.6.3
  vm_service: ^11.10.0

#dependency_overrides:
#  data_serializer:
#    path: ../data_serializer
#  async_events:
#    path: ../async_events
#  map_history:
#    path: ../map_history
#  mercury_client:
#    path: ../mercury_client
#  async_extension:
#    path: ../async_extension
#  dart_spawner:
#    path: ../dart_spawner
#  reflection_factory:
#    path: ../reflection_factory
#  statistics:
#    path: ../statistics
#  docker_commander:
#    path: ../docker_commander
#  shelf_letsencrypt:
#    path: ../shelf_letsencrypt
#  swiss_knife:
#    path: ../swiss_knife
